export class CooperativeSociety {
    societyId: number = 0;//autogenerated
  societyName: string = '';
  headOfSociety: string = '';
  village: string = '';
  district: string = '';
  pincode: string = '';
    }
