
    import { CooperativeSociety } from './cooperative-society';
    import { NominatedCandidate } from './nominated-candidate';
    import { Registeredsocietyvoters } from './registeredsocietyvoters';
    export class VotedList {
      
      id: number = 0; //autogenerated
      registeredSocietyVoters: Registeredsocietyvoters[]=[];
      nominatedcandidate: NominatedCandidate[]=[];
      cooperativesociety: CooperativeSociety[]=[];
    
      
    }
    